### ISSUE TITLE
utilizing - Or: on bucket-encryption scans

### ISSUE THREAD

**Issue by KarlCF** [cloud-custodian/cloud-custodian#6083]
**Describe the bug**
Whenever I run the following policy, I get the errors exemplified

**To Reproduce**
Run the policy

**Expected behavior**
To scan the scenarios provided

**Background (please complete the following information):**
 - OS: Linux Mint Tricia 19.3
 - Python Version: python 3.8.5
 - Custodian Version:  0.9.4
 - Cloud Provider: AWS
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: s3-encryption-4-dummies
    resource: s3
    filters:
      - or:
        - type: bucket-encryption
          state: False
        - type: bucket-encryption
          state: True
          crypto: aws:kms
          key: alias/aws/s3
        - type: bucket-encryption
          state: True
          crypto: AES256
```
 - Traceback: [if applicable, please exclude sensitive/account information]
2020-08-28 18:37:16,469: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: avk-testing-cloudtrail
2020-08-28 18:37:16,479: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: cf-templates-1cez0zyz1a4v3-sa-east-1
2020-08-28 18:37:16,485: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: cf-templates-1cez0zyz1a4v3-us-east-1
2020-08-28 18:37:16,485: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: ##################
2020-08-28 18:37:16,485: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: ##################
2020-08-28 18:37:16,504: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: ##################
2020-08-28 18:37:16,677: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: ##################
2020-08-28 18:37:16,686: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: ##################
2020-08-28 18:37:16,692: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: ##################
2020-08-28 18:37:16,692: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: ##################
2020-08-28 18:37:16,693: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: ##################
2020-08-28 18:37:16,711: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: ##################
2020-08-28 18:37:16,713: custodian.policy:INFO policy:s3-encryption-4-dummies resource:s3 region:us-east-1 count:2 time:3.54

 - `custodian version --debug` output:
Custodian:   0.9.4
Python:      3.8.5 (default, Jul 22 2020, 18:54:26) 
             [GCC 5.4.0 20160609]
Platform:    posix.uname_result(sysname='Linux', nodename='karl-mint', release='5.4.0-42-generic', version='#46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020', machine='x86_64')
Using venv:  False
Docker: False
Installed: 

argcomplete==1.12.0
attrs==19.3.0
boto3==1.14.31
botocore==1.17.31
docutils==0.15.2
importlib-metadata==1.7.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==49.2.0
six==1.15.0
tabulate==0.8.7
urllib3==1.25.10
zipp==3.1.0

**Comment by ivanivanovicdimov** [comment]
Running into the same issue, it doesn't come up when only one filter is applied but when there is multiple checking for different things it does. Doing more digging but please let me know if you found a solid solution.

**Comment by KarlCF** [comment]
No updates on my side so far, for me it would be critical to use this filter, because of compliance requirements

**Comment by jmwaks** [comment]
@kapilt , any feedback on this issue ? This was working on 0.8.33.0 but we are seeing an issue on 0.9.5

**Comment by rsandhu2** [comment]
Running into this same issue as well. @kapilt will appreciate any bugfix that can resolve this issue!

**Comment by kapilt** [comment]
fixed in #6442
