### ISSUE TITLE
gcp.loadbalancer-address: get_label_params/get crash with AttributeError on global addresses

### ISSUE THREAD

**Issue by tjs-rubrik** [cloud-custodian/cloud-custodian#10954]
### Describe the bug

`gcp.loadbalancer-address` policies that use the new `set-labels` action (or trigger a `get` refresh) crash with `AttributeError: 'NoneType' object has no attribute 'groups'` whenever the account contains a **global** loadbalancer address (`.../projects/<proj>/global/addresses/<name>`). The `parse_params()` helper added in #10774 uses a regex that only matches the **regional** address selfLink shape (`.../regions/<r>/addresses/<name>`), so `re.match(...)` returns `None` on global addresses and the subsequent `.groups()` call blows up.

`enum_spec` for this resource type is `('aggregatedList', 'items.*.addresses[]', None)`, which returns BOTH regional and global addresses in a single call, so any account that has even one global address (very common — VPC-peering / PSA / Cloud SQL Private Service Access all allocate global INTERNAL addresses) will error out on every run of any labeling policy that touches this type.

### What did you expect to happen?

Either:
1. `gcp.loadbalancer-address` should skip global addresses at enum time (they belong to the separate `gcp.loadbalancer-global-address` resource type added in #10722), or
2. `parse_params` should recognize both shapes and `get_label_params` / `get` should route to the correct API surface (`client.globalAddresses().setLabels()` vs `client.addresses().setLabels()`).

Option 1 is arguably the cleanest since a distinct global-address resource type already exists.

### Cloud Provider

Google Cloud (GCP)

### Cloud Custodian version and dependency information

```
Custodian: c7n_gcp bundled at cloud-custodian@726657d5 (2026-05)
Python:    3.14.6
```

Bug was introduced by #10774 (merged 2026-05-05) which added `set-labels` support for this resource type. Prior to that PR, `parse_params` didn't exist and the old `get()` used `resource_info['resourceName'].rsplit('/', 1)[-1]` which happened to work for both shapes.

### Policy

Minimal repro — any policy with a mode/action that triggers `get_label_params` or `get()`:

```yaml
policies:
  - name: gcp-loadbalancer-address-tag-example
    resource: gcp.loadbalancer-address
    actions:
      - type: set-labels
        labels:
          rbrk_env: prod
```

The policy filter phase succeeds and reports the correct match count (we see `count:2` in the log — 2 global addresses matched), then the action phase crashes.

### Relevant log/traceback output

```
2026-07-30 17:40:01,404 - custodian.policy - INFO - policy:gcp_loadbalancer_address_rbrk_tags_default resource:gcp.loadbalancer-address region: count:2 time:0.80
2026-07-30 17:40:01,438 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/app/.venv/lib/python3.14/site-packages/c7n/policy.py", line 364, in run
    results = a.process(resources)
  File "/app/.venv/lib/python3.14/site-packages/c7n_gcp/actions/core.py", line 65, in process
    self.process_resource_set(client, model, resource_set)
  File "/app/.venv/lib/python3.14/site-packages/c7n_gcp/actions/core.py", line 72, in process_resource_set
    params = self.get_resource_params(model, resource)
  File "/app/.venv/lib/python3.14/site-packages/c7n_gcp/actions/labels.py", line 57, in get_resource_params
    return model.get_label_params(resource, all_labels)
  File "/app/.venv/lib/python3.14/site-packages/c7n_gcp/resources/loadbalancer.py", line 48, in get_label_params
    project, region, address = cls.parse_params(resource['selfLink'])
  File "/app/.venv/lib/python3.14/site-packages/c7n_gcp/resources/loadbalancer.py", line 35, in parse_params
    return re.match(exp, resc_name).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

### Sample offending selfLinks

Real production examples (VPC peering / CloudSQL PSA addresses):

```
https://www.googleapis.com/compute/v1/projects/<project-a>/global/addresses/rubrik-exo-rubrik-gaia-next-cloudsql-psa-address-23-us-central1
https://www.googleapis.com/compute/v1/projects/<project-a>/global/addresses/rubrik-exo-rubrik-gai-cloudsql-psa-23-us-central1
https://www.googleapis.com/compute/v1/projects/<project-b>/global/addresses/rubrik-exo-rubrik-gaia-cloudsql-psa-address-23-us-central1
https://www.googleapis.com/compute/v1/projects/<project-b>/global/addresses/rubrik-exo-rubrik-gai-cloudsql-psa-23-us-central1
```

All four have `addressType: INTERNAL`, `purpose: VPC_PEERING`, and `region` field is `null`.

### Suggested fix (Option 2, minimal change)

If you prefer to keep global addresses inside `gcp.loadbalancer-address`, widen the regex and branch in the label params:

```python
_REGIONAL_RE = re.compile(r".*projects/([^/]+)/regions/([^/]+)/addresses/(.+)")
_GLOBAL_RE   = re.compile(r".*projects/([^/]+)/global/addresses/(.+)")

@staticmethod
def parse_params(resc_name):
    m = _REGIONAL_RE.match(resc_name)
    if m:
        project, region, address = m.groups()
        return project, region, address
    m = _GLOBAL_RE.match(resc_name)
    if m:
        project, address = m.groups()
        return project, None, address
    raise ValueError(f"unrecognized address selfLink: {resc_name}")

@classmethod
def get_label_params(cls, resource, all_labels):
    project, region, address = cls.parse_params(resource['selfLink'])
    params = {
        'project': project,
        'resource': address,
        'body': {'labels': all_labels, 'labelFingerprint': resource['labelFingerprint']},
    }
    if region is not None:
        params['region'] = region
    return params
```

...and in `LabelActionMixin` (or equivalent) route to `client.globalAddresses().setLabels()` when `region is None`.

### Suggested fix (Option 1, cleaner architecturally)

Filter global addresses out of the aggregated enum for `gcp.loadbalancer-address` and rely on `gcp.loadbalancer-global-address` (added in #10722) for global address labeling.

Happy to open a PR for either approach if a maintainer confirms which they prefer.

### Related

- #10774 introduced the `parse_params` regex (2026-05-05).
- #10722 added `gcp.loadbalancer-global-address` as a separate resource type (2026-04-29).

**Comment by ajkerrigan** [comment]
Option 1 is cleaner architecturally _but_ means that folks who were using `gcp.loadbalancer-address` before the global resource type existed would get the surprise of resources seeming to disappear from their result sets. Doable, but we'd need to be careful about communicating that.

Prior to that (or as a more backward-compatible alternative), we could warn-and-skip those global addresses as part of the labeling action, with guidance to nudge folks toward the global resource type for labeling global addresses.

That also suggests a policy-level workaround that would avoid this issue today:

```yaml
filters:
  - not:
    - type: value
      key: selfLink
      op: */global/addresses/*
```
