### ISSUE TITLE
ci - trunk failure on py2.7

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#3310]
in ci, we're getting repeated failures for 2.7 since merging #3306 (unrelated to that pr), with all tests failing, reporting the same issue 

```
2019-01-06T15:17:13.1442244Z   File "/home/vsts/work/1/s/.tox/py27-cov/lib/python2.7/site-packages/pytest_cov/plugin.py", line 289, in pytest_runtest_call
2019-01-06T15:17:13.1442832Z     if (item.get_marker('no_cover')
2019-01-06T15:17:13.1443030Z AttributeError: 'TestCaseFunction' object has no attribute 'get_marker'
```

looking through pytest history, they had a release recently, but we've had a few successful builds since then.
https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst#pytest-410-2019-01-05

oddly tox works locally without issue  and the same 4.1.0 release

```
$ tox -e py27
GLOB sdist-make: /Users/kapilt/projects/custodian/setup.py
py27 create: /Users/kapilt/projects/custodian/.tox/py27
py27 installdeps: -rrequirements-dev.txt, -rtools/c7n_mailer/requirements.txt, -rtools/c7n_azure/requirements.txt, -rtools/c7n_gcp/requirements.txt, -rtools/c7n_kube/requirements.txt
py27 inst: /Users/kapilt/projects/custodian/.tox/.tmp/package/1/c7n-0.8.33.1.zip
py27 installed: adal==1.0.2,alabaster==0.7.12,apipkg==1.5,applicationinsights==0.11.7,argcomplete==1.9.4,asn1crypto==0.24.0,atomicwrites==1.2.1,attrs==18.2.0,aws-xray-sdk==2.2.0,azure-cli-core==2.0.40,azure-cli-nspkg==3.0.3,azure-common==1.1.16,azure-graphrbac==0.53.0,azure-mgmt-applicationinsights==0.1.1,azure-mgmt-authorization==0.51.1,azure-mgmt-batch==5.0.1,azure-mgmt-cdn==3.0.0,azure-mgmt-cognitiveservices==3.0.0,azure-mgmt-compute==4.4.0,azure-mgmt-containerservice==4.3.0,azure-mgmt-cosmosdb==0.5.2,azure-mgmt-datafactory==0.6.0,azure-mgmt-datalake-nspkg==3.0.1,azure-mgmt-datalake-store==0.5.0,azure-mgmt-eventgrid==2.0.0rc2,azure-mgmt-iothub==0.7.0,azure-mgmt-keyvault==1.1.0,azure-mgmt-monitor==0.5.2,azure-mgmt-network==2.4.0,azure-mgmt-nspkg==3.0.2,azure-mgmt-policyinsights==0.2.0,azure-mgmt-redis==5.0.0,azure-mgmt-resource==2.1.0,azure-mgmt-sql==0.11.0,azure-mgmt-storage==3.1.1,azure-mgmt-subscription==0.2.0,azure-mgmt-web==0.40.0,azure-nspkg==3.0.2,azure-storage-blob==1.4.0,azure-storage-common==1.4.0,azure-storage-nspkg==3.1.0,azure-storage-queue==1.4.0,Babel==2.6.0,backports.functools-lru-cache==1.5,bcrypt==3.1.5,bleach==3.0.2,boto3==1.9.74,botocore==1.12.74,c7n==0.8.33.1,-e git+https://github.com/kapilt/cloud-custodian@977fd64737c237acd1df0e2946fadbcb7456fbbc#egg=c7n_azure&subdirectory=tools/c7n_azure,-e git+https://github.com/kapilt/cloud-custodian@977fd64737c237acd1df0e2946fadbcb7456fbbc#egg=c7n_gcp&subdirectory=tools/c7n_gcp,-e git+https://github.com/kapilt/cloud-custodian@977fd64737c237acd1df0e2946fadbcb7456fbbc#egg=c7n_kube&subdirectory=tools/c7n_kube,-e git+https://github.com/kapilt/cloud-custodian@977fd64737c237acd1df0e2946fadbcb7456fbbc#egg=c7n_mailer&subdirectory=tools/c7n_mailer,-e git+https://github.com/kapilt/cloud-custodian@977fd64737c237acd1df0e2946fadbcb7456fbbc#egg=c7n_org&subdirectory=tools/c7n_org,-e git+https://github.com/kapilt/cloud-custodian@977fd64737c237acd1df0e2946fadbcb7456fbbc#egg=c7n_sphinxext&subdirectory=tools/c7n_sphinxext,cachetools==3.0.0,certifi==2018.11.29,cffi==1.11.5,chardet==3.0.4,Click==7.0,colorama==0.4.1,configparser==3.5.0,contextlib2==0.5.5,coverage==4.5.2,cryptography==2.4.2,datadog==0.26.0,decorator==4.3.0,distlib==0.2.8,docutils==0.14,enum34==1.1.6,execnet==1.5.0,fakeredis==0.16.0,filelock==3.0.10,flake8==3.5.0,funcsigs==1.0.2,functools32==3.2.3.post2,future==0.17.1,futures==3.2.0,google-api-core==1.7.0,google-api-python-client==1.7.4,google-auth==1.6.2,google-auth-httplib2==0.0.3,google-cloud-core==0.29.1,google-cloud-logging==1.9.1,google-cloud-monitoring==0.31.1,googleapis-common-protos==1.5.5,grpcio==1.17.1,httplib2==0.12.0,humanfriendly==4.17,idna==2.8,imagesize==1.1.0,ipaddress==1.0.22,isodate==0.6.0,Jinja2==2.10,jmespath==0.9.3,jsonpatch==1.23,jsonpickle==1.0,jsonpointer==2.0,jsonschema==2.6.0,knack==0.3.3,kubernetes==7.0.0,ldap3==2.5.2,markup==0.2,MarkupSafe==1.0,mccabe==0.6.1,mock==2.0.0,monotonic==1.5,more-itertools==5.0.0,msrest==0.6.2,msrestazure==0.6.0,nose==1.3.7,nose-timer==0.7.4,oauthlib==2.1.0,packaging==18.0,paramiko==2.4.2,pathlib2==2.3.3,pbr==5.1.1,pkginfo==1.4.2,placebo==0.8.1,pluggy==0.8.0,protobuf==3.6.1,psutil==5.4.8,py==1.7.0,pyasn1==0.4.5,pyasn1-modules==0.2.3,pycodestyle==2.3.1,pycparser==2.19,pyflakes==1.6.0,Pygments==2.3.1,PyJWT==1.7.1,PyNaCl==1.3.0,pyOpenSSL==18.0.0,pyparsing==2.3.0,pytest==4.1.0,pytest-cov==2.6.0,pytest-forked==0.2,pytest-xdist==1.25.0,python-dateutil==2.7.5,python-http-client==3.1.0,pytz==2018.7,PyYAML==3.13,ratelimiter==1.2.0.post0,readme-renderer==24.0,redis==3.0.1,requests==2.21.0,requests-oauthlib==1.0.0,requests-toolbelt==0.8.0,retrying==1.3.3,rsa==4.0,ruamel.ordereddict==0.4.13,ruamel.yaml==0.15.42,s3transfer==0.1.13,scandir==1.9.0,sendgrid==5.6.0,six==1.11.0,slackclient==1.3.0,snowballstemmer==1.2.1,Sphinx==1.7.6,sphinx-rtd-theme==0.4.1,sphinxcontrib-websupport==1.1.0,tabulate==0.8.2,toml==0.10.0,tox==3.6.1,tqdm==4.28.1,twine==1.12.1,typing==3.6.6,uritemplate==3.0.0,urllib3==1.24.1,vcrpy==1.11.0,vcrpy-unittest==0.1.7,vcversioner==2.16.0.0,virtualenv==16.2.0,webencodings==0.5.1,websocket-client==0.54.0,wrapt==1.10.11                                                                                        
py27 run-test-pre: PYTHONHASHSEED='23242779'
py27 runtests: commands[0] | py.test -n auto --junitxml=junit/test-results.xml tests tools
==================================================================================== test session starts =====================================================================================
platform darwin -- Python 2.7.15, pytest-4.1.0, py-1.7.0, pluggy-0.8.0
cachedir: .tox/py27/.pytest_cache
rootdir: /Users/kapilt/projects/custodian, inifile: tox.ini
plugins: xdist-1.25.0, forked-0.2, cov-2.6.0
gw0 [1393] / gw1 [1393] / gw2 [1393] / gw3 [1393] / gw4 [1393] / gw5 [1393] / gw6 [1393] / gw7 [1393]
...................................................................................................................................................................................... [ 13%]
...................................................................................................................................................................................... [ 26%]
...................................................................................................................................................................................... [ 39%]
...................................................................................................................................................................................... [ 52%]
...................................................................................................................................................................................... [ 65%]
...................................................................................................................................................................................... [ 78%]
......................................s.s............................................................................................................................................. [ 91%]
...................................................................................................ssss.s..............                                                                [100%]
-------------------------------------------------------- generated xml file: /Users/kapilt/projects/custodian/junit/test-results.xml ---------------------------------------------------------
========================================================================== 1386 passed, 7 skipped in 118.15 seconds ==========================================================================
__________________________________________________________________________________________ summary ___________________________________________________________________________________________
  py27: commands succeeded
  congratulations :)
```

**Comment by kapilt** [comment]
`tox -e py27-cov` also reproduces locally

**Comment by kapilt** [comment]
manually running the commands executed by py27-cov, gets a different result, which is some failures but more like 7 failures, which look odd but debuggable, where as in ci or with tox -e py27-cov its 100% failures across ~1400 tests.

**Comment by kapilt** [comment]
pinning pytest version <4.1.0 seems to resolve

**Comment by kapilt** [comment]
this seems to be the root cause https://github.com/pytest-dev/pytest/issues/4606

**Comment by kapilt** [comment]
its fixed upstream in pytest-cov plugin, but till there's a release, we will pin.
