### ISSUE TITLE
Azure - Errors off latest build with python3.8 - unable to deploy

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#5080]
Pulled latest code, tried to run in python 3.8 virtual env and received the following errors:
```2019-11-15 14:19:09,611: custodian.azure.session:ERROR Failed to authenticate.
Traceback (most recent call last):
  File "/Users/t275053/Dev/cloud-custodian/custodian-mgmtgrp11/lib/python3.8/site-packages/c7n_azure/session.py", line 146, in _initialize_session
    self._authenticate()
  File "/Users/t275053/Dev/cloud-custodian/custodian-mgmtgrp11/lib/python3.8/site-packages/c7n_azure/session.py", line 102, in _authenticate
    result = instance.authenticate()
  File "/Users/t275053/Dev/cloud-custodian/custodian-mgmtgrp11/lib/python3.8/site-packages/c7n_azure/session.py", line 349, in authenticate
    tenant_id) = Profile().get_login_credentials(resource=self.resource_namespace)
  File "/Users/t275053/Dev/cloud-custodian/custodian-mgmtgrp11/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 145, in __init__
    self.cli_ctx = cli_ctx or get_default_cli()
  File "/Users/t275053/Dev/cloud-custodian/custodian-mgmtgrp11/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 546, in get_default_cli
    return AzCli(cli_name='az',
  File "/Users/t275053/Dev/cloud-custodian/custodian-mgmtgrp11/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 55, in __init__
    SESSION.load(os.path.join(azure_folder, 'az.sess'), max_age=3600)
  File "/Users/t275053/Dev/cloud-custodian/custodian-mgmtgrp11/lib/python3.8/site-packages/azure/cli/core/_session.py", line 46, in load
    if st.st_mtime + max_age < time.clock():
AttributeError: module 'time' has no attribute 'clock'
```
Is this pegged to run on 3.7.4 or earlier?

**Comment by kapilt** [comment]
this is an underlying issue (one of many re #5017 and upstream https://github.com/Azure/azure-sdk-for-python/issues/8662) with the azure sdks, this was filed upstream on the sdks recently for python 3.8 compatibility issues.

nutshell custodian works fine for any other provider but azure, but azure sdks don't work with python 3.8. this has been warning in their ci for the entirety of 3.7.

**Comment by kapilt** [comment]
afaics, they seemed to have released updated sdks for azure that resolve the time.clock removal, I've put up a pr to add in python 3.8 as a test runner, and it seems to work okay.

**Comment by kapilt** [comment]
this is an upstream issue afaics, not something the custodian project or community can fix.

**Comment by stefangordon** [comment]
For tracking there is also an issue filed on the syntax/warning issues in the storage SDK that create a bunch of log noise

https://github.com/Azure/azure-storage-python/issues/664
